### ISSUE TITLE
508 Issues - Apply Page

### ISSUE THREAD

**Issue by nickbristow** [WhiteHouse/usds-website#28]
1. For 508, the goal is 4.5:1, this can be verified with any OTS color contrast analyzer. I only noticed a couple spots (not counting the header and footer, from the parent site) where it missed
  *  ![us_digital_service_-_apply___the_white_house](https://cloud.githubusercontent.com/assets/5296248/5825439/44338c20-a0b9-11e4-87f3-4ed7d17f2933.png)
  *  ![us_digital_service_-_apply___the_white_house](https://cloud.githubusercontent.com/assets/5296248/5825460/6eef6cf4-a0b9-11e4-81ec-4ce5789082bc.png)
2. Use fieldset and legend for groups of form inputs
  * Example Skill should be the legend for the following checkboxes. This pattern should be used for all the checkbox fields
  * ![us_digital_service_-_apply___the_white_house](https://cloud.githubusercontent.com/assets/5296248/5825600/99104f52-a0ba-11e4-907f-095055b382c1.png)
3. All form input fields need a label or descriptive title attribute
  * For the where can we find you online fields, add "Where can we find you... example github" etc

**Comment by NoahKunin** [comment]
:+1: 

508 applies to everything, obviously, but this is especially meaningful on forms, and even more meaningful on recruiting a diverse team. Thanks @nickbristow!

**Comment by mollieru** [comment]
@kathytpham can you work with the Salesforce team to apply the above 508 fixes to the application? 

Curious why they didn't just apply the same styles from the PIF form, which I assume was also fixed for 508. Also, in general, would be nice if they knew to anticipate 508 from the start...

**Comment by kathytpham** [comment]
Thank you for flagging these!

Do you know if the PIF application has similar issues? It is the same company that built both so it would help to know if I can ask them to talk to each other. 

@nickbristow, Can I connect you and your expertise to the Salesforce folks in EOP?

**Comment by nickbristow** [comment]
I will check, I haven't had a chance to review it. 

-Nick Bristow

**Comment by kathytpham** [comment]
Nick, what's the preferred email I should use for you when I connect with
the Salesforce team? Is it OK to cc you?

On Fri, Jan 23, 2015 at 1:28 PM, Nick Bristow <notifications@github.com>
wrote:

> I will check, I haven't had a chance to review it.
>
> -Nick Bristow
>
> > On Jan 23, 2015, at 1:09 PM, kathytpham <notifications@github.com>
> wrote:
> >
> > Thank you for flagging these!
> >
> > Do you know if the PIF application has similar issues? It is the same
> company that built both so it would help to know if I can ask them to talk
> to each other.
> >
> > @nickbristow, Can I connect you and your expertise to the Salesforce
> folks in EOP?
> >
> > \
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhiteHouse/usds-website/issues/28#issuecomment-71239838>
> .
>



-- 
912-220-6423
kathytpham@gmail.com

**Comment by mollieru** [comment]
Same Q -- is this resolved?

**Comment by kimballce** [comment]
This was resolved back in Jan.

**Comment by mollieru** [comment]
great, thanks!

**Comment by jennifer6** [comment]
Cool. Please close.



Sent with Good (www.good.com)


-----Original Message-----
