### ISSUE TITLE
Ensure new USDS pages include "cards" for Facebook and Twitter. Currently FB features a card that says "404 Page Not Found"

### ISSUE THREAD

**Issue by jtag** [WhiteHouse/usds-website#30]
Sample view when posting links on FB...

![screen shot 2015-01-21 at 4 00 55 pm](https://cloud.githubusercontent.com/assets/339243/5845328/167f0f68-a189-11e4-8d76-638e54d4fadc.png)

**Comment by mollieru** [comment]
@jtag i believe we've fixed this -- would you mind checking to confirm?

**Comment by jtag** [comment]
looks great on Facebook!
