### ISSUE TITLE
Missing HTTPS

### ISSUE THREAD

**Issue by konklone** [WhiteHouse/usds-website#32]
I know it's not within the USDS team's direct control - but the USDS website doesn't currently offer a secure connection. Any ISP, foreign government, or cafe could freely intercept or modify the website.

Specifically, a certificate at [`www.whitehouse.gov`](https://www.whitehouse.gov) is valid only for Akamai, and a certificate at [`whitehouse.gov`](https://whitehouse.gov) is only valid for `*.whitehouse.gov`:

![whitehouse-www](https://cloud.githubusercontent.com/assets/4592/5861665/98b9b838-a239-11e4-8bb3-2225d91d3a94.png)

![whitehouse](https://cloud.githubusercontent.com/assets/4592/5861646/65a14b32-a239-11e4-84ad-4b6e552896cb.png)

**Comment by NoahKunin** [comment]
:+1: x :100:

**Comment by mollieru** [comment]
@kathytpham can explain further, but I know the application is on HTTPS (iframed in). @willchan and others are working on a longer term, less janky solution. we all agree this is sub-ideal.

**Comment by konklone** [comment]
That's great to hear. (FWIW, right now the source code on http://www.whitehouse.gov/digital/united-states-digital-service has two `<iframe>` tags, both of which point to `http://` URLs.)

**Comment by willchan** [comment]
The https iframe (obviously trivially bypassed by active network attackers)
is on the "apply" page, or at least it was last I checked. But yes, we need
whitehouse.gov to move to https. More discussion later :)

**Comment by kathytpham** [comment]
Hi friends!

Thank you for looking at this so thoughtfully. We've had extensive
discussions as well. It was my decision along with the folks in ODS at the
White House and the Salesforce team to go with the iFrame route. Our
current options are below:

1) Host HTTPS iFrame inside HTTP site. The iframe points to:
https://whitehouse.secure.force.com/digitalserviceform
2) Redirect to the HTTPS non-Whitehouse force.com URL:
https://whitehouse.secure.force.com/digitalserviceform

Neither options are ideal. In the end, we decided that #1 is our best
option at the moment. Users look at the HTTP and they may think "Oh noes!
My PII!," but we decided it was better than redirecting to
https://somethingweirdnotwhitehouse.

After SOTU, there are plans to get wh.gov to some TSL love. Leigh over at
the White House is aware of all of this.

I hope that helps!

Kathy

On Thu, Jan 22, 2015 at 7:47 PM, William Chan <notifications@github.com>
wrote:

> The https iframe (obviously trivially bypassed by active network
> attackers)
> is on the "apply" page, or at least it was last I checked. But yes, we
> need
> whitehouse.gov to move to https. More discussion later :)
>
> On Thu, Jan 22, 2015, 7:10 PM Eric Mill <notifications@github.com> wrote:
>
> > That's great to hear. (FWIW, right now the source code on
> > http://www.whitehouse.gov/digital/united-states-digital-service has two
> > <iframe> tags, both of which point to http:// URLs.)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/WhiteHouse/usds-website/issues/32#issuecomment-71125592>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhiteHouse/usds-website/issues/32#issuecomment-71129229>
> .
>



-- 
912-220-6423
kathytpham@gmail.com

**Comment by konklone** [comment]
:+1: :smiley_cat:

**Comment by NoahKunin** [comment]
Leigh is part of the family, that's great. What the team may not know is
18F has made "TLS provisioning" much easier, *almost* painless.

@konklone in the next 2 weeks, might be good for us to demo for them?

On Thursday, January 22, 2015, Eric Mill <notifications@github.com> wrote:

> [image: :+1:] [image: :smiley_cat:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhiteHouse/usds-website/issues/32#issuecomment-71143127>
> .
>


-- 
Noah Kunin
Delivery Architecture + Infrastructure Services Director
202-577-7167 | @18F <https://twitter.com/18F>

**Comment by kathytpham** [comment]
Love! Thanks for working on that so it is easier for the rest of us.

On Friday, January 23, 2015, Noah Kunin <notifications@github.com> wrote:

> Leigh is part of the family, that's great. What the team may not know is
> 18F has made "TLS provisioning" much easier, *almost* painless.
>
> @konklone in the next 2 weeks, might be good for us to demo for them?
>
> On Thursday, January 22, 2015, Eric Mill <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > [image: :+1:] [image: :smiley_cat:]
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/WhiteHouse/usds-website/issues/32#issuecomment-71143127>
>
> > .
> >
>
>
> --
> Noah Kunin
> Delivery Architecture + Infrastructure Services Director
> 202-577-7167 | @18F <https://twitter.com/18F>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhiteHouse/usds-website/issues/32#issuecomment-71214661>
> .
>


-- 
912-220-6423
kathytpham@gmail.com

**Comment by konklone** [comment]
:+1: Whatever people want to do. =)

**Comment by gdbelvin** [comment]
Just a ping to say this is important work!  Still 2 weeks out?

**Comment by NoahKunin** [comment]
Hi @gdbelvin! Thanks for the ping.

_Completely_ concur that this important work. There's lots of activity right now around HTTPS Everywhere in the Federal Government, both public and non-public. It's just that within the US Gov, there's never anything unimportant, so we're always triaging between "pretty important" and :fire: :fire_engine: :fireworks: stuff.

I think you'll see additional progress soon across the board. Over at 18F, here's our latest work: https://18f.gsa.gov/2015/02/09/the-first-gov-domains-hardcoded-into-your-browser-as-all-https/

You might already know about that, mainly linking to it for other visitors to this thread. Stay tuned.

**Comment by lheyman** [comment]
Folks ok if I close this one? HTTPS went out last night (HSTS in a few days):
https://twitter.com/WHWeb/status/575509388133335041

**Comment by konklone** [comment]
:+1: Totally awesome, @lheyman, and a strong symbol to the rest of the government. Congrats on getting this shipped!

**Comment by alex** [comment]
:sparkles: :cake: :sparkles: Awesome work.

On Wed, Mar 11, 2015 at 3:26 PM, Eric Mill <notifications@github.com> wrote:

> [image: :+1:] Totally awesome, @lheyman <https://github.com/lheyman>, and
> a strong symbol to the rest of the government. Congrats on getting this
> shipped!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhiteHouse/usds-website/issues/32#issuecomment-78351409>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084
