### ISSUE TITLE
Story Circles re-design?

### ISSUE THREAD

**Issue by NoahKunin** [WhiteHouse/usds-website#34]
First off, let me again thank @mollieru for pulling this together. Truly awesome given all the constraints.

My current feedback is that on `.../story`, the featured practice circles kind of get lost in a mix. It doesn't really scan for me with the vertical text under each circle.  Perhaps alternating image pulls and horizontal text?

A more thorough re-work will take time obviously, and I don't have an easy answer between other meetings. It's a nice to have, but just want to capture it here.

**Comment by mollieru** [comment]
Totally happy to revisit this. @NoahKunin can you explain and/or sketch what you mean by 'alternating image pulls'?

**Comment by mollieru** [comment]
@NoahKunin wanted to get your thoughts on this -- have any sketches or ideas for me to play w?

**Comment by mollieru** [comment]
these no longer exist. we're going to address this issue in next version of the site. thanks!
