### ISSUE TITLE
Typo in 'Stories and Press' section

### ISSUE THREAD

**Issue by atbaker** [WhiteHouse/usds-website#39]
Hi USDS team,

Congrats on being on [Hacker News today](https://news.ycombinator.com/item?id=8988819)! The site looks really slick! 

I spotted a typo while poking around and thought I'd let you know: http://www.whitehouse.gov/digital/united-states-digital-service/story

"Uncle **Same** Needs More Geeks"

I hope this is the right place to log the issue. Thanks for all that you do!

**Comment by cew821** [comment]
Thanks for flagging this! Fixed.
