### ISSUE TITLE
It is totally unclear what "Join Us" means

### ISSUE THREAD

**Issue by anthonygarvan** [WhiteHouse/usds-website#40]
Hey guys - I'm excited about the usds and would like to contribute somehow in my spare time (about 10 hrs / week). I just "Joined" on the website, and afterwards realized I actually had no idea what I had just done. Was it an application for a full time role? Application for a fellowship? Email / newsletter on steroids? Indentured servitude? I understand you are trying to make a simple, clean site, but you need some clarity. Most people will be smarter than me and not just "join" things when they don't know what they are signing up for.

**Comment by mollieru** [comment]
thank you! this is resolved in a new update to the site.
