### ISSUE TITLE
A "Join Us" link is broken

### ISSUE THREAD

**Issue by waldoj** [WhiteHouse/usds-website#41]
The blue "Join Us" button in the section titled "Teams of problem solvers making government services simple, effective, and efficient" is missing the `www.` prefix, which causes the link to redirect to the whitehouse.gov home page.

![join_us](https://cloud.githubusercontent.com/assets/656758/6810023/9bbeca2a-d234-11e4-8702-4f0ce19e5584.jpg)

The fix is to change:

```
<a href="http://whitehouse.gov/digital/united-states-digital-service/apply" class="btn btn-dark-blue" target="blank">JOIN US</a></button> 
```

to:

```
<a href="https://www.whitehouse.gov/digital/united-states-digital-service/apply" class="btn btn-dark-blue" target="blank">JOIN US</a></button> 
```

**Comment by rustypickens** [comment]
Hi there, Waldo!  Good catch.  The link is updated and I really appreciate you bringing it to our attention.


Rusty D. Pickens
Deputy Director, New Media Technologies
MCSE, CCNA, & PMP
Executive Office of the President

“Always bear in mind that your own resolution to succeed is more important than any other one thing.”  -Abraham Lincoln

www.Whitehouse.gov<http://www.Whitehouse.gov>
Engage the White House using We The People<https://petitions.whitehouse.gov/>
Contact<http://www.whitehouse.gov/contact/submit-questions-and-comments> the President online
Request<http://www.whitehouse.gov/contact/presidential-greetings-request> a Presidential Greeting

**Comment by waldoj** [comment]
:+1:
